
---
default: true

# Exceptions, example given, MD045
# MD045: false # allow image with no tag

# In-line HTML.
MD033: false
# Line lengths
MD013:
    line_length: 80
    tables: false
# First line in a file should be a top-level heading
MD041: false
